parameters:
    templating.engine.latte.class: LatteBundle\LatteEngine
    assetic.latte_formula_loader.class: LatteBundle\Bridge\Assetic\FormulaLoader
    latte.engine.class: LatteBundle\Bridge\Latte\Engine
    latte.helpers.class: LatteBundle\Bridge\Latte\Helpers
    latte.cache_dir: %kernel.cache_dir%/latte

services:
    latte.parser:
        class: Nette\Latte\Parser

    latte.compiler.factory:
        class: LatteBundle\Bridge\Nette\Latte\CompilerFactory

    latte.compiler:
        class: Nette\Latte\Compiler
        factory: [ @latte.compiler.factory, create ]

    latte.filter:
        class: LatteBundle\Bridge\Nette\Templating\LatteFilter
        arguments: [ @latte.parser, @latte.compiler ]

    latte.template_factory:
        alias: latte.template_factory.evented

    latte.template_factory.storage:
        class: LatteBundle\Bridge\Nette\Templating\TemplateFactory

    latte.template_factory.evented:
        class: LatteBundle\Bridge\Nette\Templating\EventedTemplateFactory
        arguments: [ @latte.template_factory.storage, @event_dispatcher ]

    latte.cache_storage:
        class: Nette\Caching\Storages\PhpFileStorage
        arguments: [ %latte.cache_dir%, @latte.cache_journal ]

    latte.cache_journal:
        class: Nette\Caching\Storages\FileJournal
        arguments: [ %latte.cache_dir% ]

    # TODO: integrational test
    latte.listner.cache:
        class: LatteBundle\Listener\CacheListener
        arguments: [ @latte.cache_storage ]
        tags:
            - { name: kernel.event_listener, event: latte.create_template, method: onCreateTemplate }

    # TODO: integrational test
    latte.listner.latteFilter:
        class: LatteBundle\Listener\LatteFilterListener
        arguments: [ @latte.cache_storage ]
        tags:
            - { name: kernel.event_listener, event: latte.create_template, method: onCreateTemplate }

    # TODO: integrational test
    latte.listner.helpers:
        class: LatteBundle\Listener\HelpersListener
        arguments: [ @latte.cache_storage ]
        tags:
            - { name: kernel.event_listener, event: latte.create_template, method: onCreateTemplate }

    templating.engine.latte:
        class: LatteBundle\LatteEngine
        arguments: [ @templating.name_parser, @templating.loader, @latte.template_factory ]

    assetic.latte_formula_loader:
        class: %assetic.cached_formula_loader.class% # TODO: LatteBundle should work without symfony/assetic-bundle
        arguments: [@assetic.latte_formula_loader.real, @assetic.config_cache, %kernel.debug%]
        tags:
            - { name: assetic.formula_loader, alias: latte }

    assetic.latte_formula_loader.real:
        class: %assetic.latte_formula_loader.class%

    latte.engine:
        class: %latte.engine.class%

    latte.helpers:
        class: %latte.helpers.class%
        calls:
            - [ setContainer, [ @service_container ]]
